In [1]:
import numpy as np

In [2]:
a = [i for i in range(10)]

In [3]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
b = np.array(a)

In [5]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = np.array([i for i in range(10)])

In [7]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
c = np.array(range(10))

In [9]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
type(b)

numpy.ndarray